-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS assessment_questions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  subject VARCHAR(20) NOT NULL,
  module VARCHAR(50) NOT NULL,
  type VARCHAR(20) NOT NULL DEFAULT 'choice',
  question TEXT NOT NULL,
  options JSONB,
  correct_answer INTEGER,
  analysis TEXT NOT NULL,
  difficulty VARCHAR(10) NOT NULL,
  knowledge_point VARCHAR(100) NOT NULL,
  score INTEGER NOT NULL DEFAULT 5,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS assessment_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  subject VARCHAR(20) NOT NULL,
  answers JSONB NOT NULL,
  score INTEGER NOT NULL,
  total_score INTEGER NOT NULL,
  percentage INTEGER NOT NULL,
  time_spent INTEGER NOT NULL,
  weak_points JSONB,
  suggestions JSONB,
  estimated_score_range JSONB,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE assessment_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessment_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看题目" ON assessment_questions FOR SELECT USING (true);
CREATE POLICY "所有人可提交测评结果" ON assessment_results FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可查看自己的测评结果" ON assessment_results FOR SELECT USING (true);